version: "3.9"
services:
  nginx:
    container_name: nginx
    image: nginx:1.20.2
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - "80:80"
    links:
      - nextjs
      - nestjs
  nextjs:
    container_name: nextjs
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      API_URL: "http://nestjs:5000"
    volumes:
      - ./www/client:/client/usr/src/app
      - /client/usr/src/app/node_modules
      - /client/usr/src/app/.next
    env_file:
      - ./client/.env
    depends_on:
      - mysql
      - nestjs
  nestjs:
    container_name: nestjs
    hostname: nestjs
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
    volumes:
      - ./www/server:/server/usr/src/app
      - /server/usr/src/app/node_modules
      - /server/usr/src/app/dist
      - static:/server/usr/static/
    env_file:
      - ./server/.env
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    hostname: mysql
    restart: always
    image: mysql:8.0.28
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ""
    env_file:
      - ./server/.env
    volumes:
      - mysqldb:/var/lib/mysql
volumes:
  mysqldb: {}
  static: {}

