version: "3.9"
services:
  nextjs:
    container_name: nextjs
    restart: always
    ports:
      - 3000:3000
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./packages/landingpage:/client/usr/src/app
      - /client/usr/src/app/node_modules
      - /client/usr/src/app/.next
    env_file:
      - ./client/.env
  nestjs:
    container_name: nestjs
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
        - .:/server/usr/src/app
        - /server/usr/src/app/node_modules
    env_file:
      - ./server/.env
  mysql:
    container_name: mysql
    restart: always
    image: mysql:8.0.28
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    env_file:
      - ./server/.env

